include("booleanalgebra.jl")
include("g3.jl")
include("g4.jl")
include("g5.jl")
# include("h4.jl")
# include("h9.jl")
# include("l3.jl")
# include("l4.jl")
# include("sixvaluedalgebras/sixvaluedalgebras.jl")
